# Programmation linéaire

## Flot Maximal

<img src="./elementaire.svg" width="600">

**VARIABLES**
On appelera $q_{AB}$ le flot le long de l'arrête reliant $A$ à $B$.
Et on adaptera la notation pour les autres arrêtes $q_{AC},q_{BD},q_{CB},q_{CD}$

**CONTRAINTES ARRETES**
On a les contraintes dûes aux capacité des arrêtes:
\begin{align}
0 \leq q_{AB} \leq 4& &\text{ arrete } AB\\
0 \leq q_{AC} \leq 5& &\text{ arrete } AC\\
0 \leq q_{BD} \leq 5& &\text{ arrete } BD\\
0 \leq q_{CB} \leq 2& &\text{ arrete } CB\\
0 \leq q_{CD} \leq 4& &\text{ arrete } CD
\end{align}

**CONTRAINTES NOEUDS** sauf à la source $A$, et au puit $D$

\begin{align}
q_{AB} + q_{CB} = q_{BD}& &\text{ au noeud } B\\
q_{AC} = q_{CB} + q_{CD}& &\text{ au noeud } C
\end{align}

**OBJECTIF**

$$
\max q_{AB} + q_{AC}
$$
ou de manière équivalente
$$
\max q_{BD} + q_{CD}
$$

**REMARQUE** 
- le problème de flot maximal est bien un problème de programmation linéaire.
- l'algorithme utilisé la séance dernière est plus efficace que les algorithmes de programmation linéaire.

**CALCUL EQUIVALENCE**
5 min -> 10h35

Pourquoi a-t-on 
$$q_{AB} + q_{AC} = q_{BD} + q_{CD}$$
lorsque les contraintes sont satisfaites?

**ETAPE 1** on ajoute toutes les égalités aux noeuds.

$$
q_{AB} + q_{CB} + q_{AC} = q_{BD} + q_{CB} + q_{CD}
$$

**ETAPE 2** on élimine les quantités présentes des deux côtés
$$
q_{AB} + q_{AC} = q_{BD} + q_{CD}
$$

**COMPLEMENT** expliquer pourquoi cette démarche marche de manière générale.

## Reformulation

On introduit des arrêtes artificielles entrant dans la source et sortant du puit.

<img src="./elementaire_bis.svg" width="600">

**VARIABLES**

$q_s, q_{AB}, q_{AC},q_{BD},q_{CB},q_{CD}, q_p$

**CONTRAINTES ARRETES**

\begin{align}
&0\leq q_s&\\
&0 \leq q_{AB} \leq 4 &\text{ arrete } AB\\
&0 \leq q_{AC} \leq 5 &\text{ arrete } AC\\
&0 \leq q_{BD} \leq 5 &\text{ arrete } BD\\
&0 \leq q_{CB} \leq 2 &\text{ arrete } CB\\
&0 \leq q_{CD} \leq 4 &\text{ arrete } CD\\
&0\leq q_p&
\end{align}

**CONTRAINTES NOEUDS**

\begin{align}
&q_s = q_{AB} + q_{AC} &\text{ au noeud } A\\
&q_{AB} + q_{CB} = q_{BD} &\text{ au noeud } B\\
&q_{AC} = q_{CB} + q_{CD} &\text{ au noeud } C\\
& q_{BD} + q_{CD} = q_p &\text{ au noeud } D
\end{align}

**OBJECTIF**

$$\max q_s$$
ou de manière équivalente (là encore il suffit de sommet toutes les égalités aux sommets)
$$\max q_p$$

## Résolution avec `scipy`

In [1]:
from scipy.optimize import linprog

In [2]:
import numpy as np

### Exercice
10min -> 11h

Résolvez les programmes linéaires ci-dessus avec `linprog`.


In [4]:
c = np.array([-1, 0, 0, 0, 0, 0, 0])
c

array([-1,  0,  0,  0,  0,  0,  0])

In [11]:
A_ub = np.matrix("""
-1 0 0 0 0 0 0;
0 -1 0 0 0 0 0;
0 0 -1 0 0 0 0;
0 0 0 -1 0 0 0;
0 0 0 0 -1 0 0;
0 0 0 0 0 -1 0;
0 0 0 0 0 0 -1;
0 1 0 0 0 0 0;
0 0 1 0 0 0 0;
0 0 0 1 0 0 0;
0 0 0 0 1 0 0;
0 0 0 0 0 1 0
""")
A_ub = np.array(A_ub)
A_ub

array([[-1,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0],
       [ 0,  0,  0,  0,  0,  0, -1],
       [ 0,  1,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  0]])

In [6]:
A_ub.shape

(12, 7)

In [7]:
b_ub = np.array([0, 0, 0, 0, 0, 0, 0, 4, 5, 5, 2, 4])
b_ub

array([0, 0, 0, 0, 0, 0, 0, 4, 5, 5, 2, 4])

In [12]:
A_eq = np.matrix("""
1 -1 -1 0 0 0 0;
0 1 0 -1 1 0 0;
0 0 1 0 -1 -1 0;
0 0 0 1 0 1 -1
""")
A_eq = np.array(A_eq)
A_eq

array([[ 1, -1, -1,  0,  0,  0,  0],
       [ 0,  1,  0, -1,  1,  0,  0],
       [ 0,  0,  1,  0, -1, -1,  0],
       [ 0,  0,  0,  1,  0,  1, -1]])

In [13]:
b_eq = np.array(4 * [0])
b_eq

array([0, 0, 0, 0])

In [15]:
solution = linprog(c=c, A_eq=A_eq, b_eq=b_eq, A_ub=A_ub, b_ub=b_ub)
print(solution)

     con: array([ 3.92486044e-12, -3.82782694e-12,  4.02966549e-12, -3.95417032e-12])
     fun: -8.999999999912182
 message: 'Optimization terminated successfully.'
     nit: 5
   slack: array([9.00000000e+00, 4.00000000e+00, 5.00000000e+00, 5.00000000e+00,
       1.00000000e+00, 4.00000000e+00, 9.00000000e+00, 2.61133337e-11,
       5.77795589e-11, 5.76498849e-11, 1.00000000e+00, 2.60409472e-11])
  status: 0
 success: True
       x: array([9., 4., 5., 5., 1., 4., 9.])


In [16]:
linprog(c=c, A_eq=A_eq, b_eq=b_eq, A_ub=A_ub, b_ub=b_ub, method="simplex")

     con: array([0., 0., 0., 0.])
     fun: -9.0
 message: 'Optimization terminated successfully.'
     nit: 9
   slack: array([9., 4., 5., 5., 1., 4., 9., 0., 0., 0., 1., 0.])
  status: 0
 success: True
       x: array([9., 4., 5., 5., 1., 4., 9.])

In [17]:
linprog(c=c, A_eq=A_eq, b_eq=b_eq, A_ub=A_ub, b_ub=b_ub, method="highs")

           con: array([0., 0., 0., 0.])
 crossover_nit: 0
           fun: -9.0
       message: 'Optimization terminated successfully.'
           nit: 3
         slack: array([9., 4., 5., 5., 1., 4., 9., 0., 0., 0., 1., 0.])
        status: 0
       success: True
             x: array([9., 4., 5., 5., 1., 4., 9.])

**REMARQUE** 

le simplexe est présent pour des raisons historiques, on préférera les autres solvers en particulier les `highs` récents.

**REMARQUE**

- On rentre manuellement les matrices ce qui peut être source d'erreur vue la quantité de coefficients.
- La modélisation est faite manuellement.
- De plus on ne peut résoudre que des problèmes linéaires en variable continue.

## Exemple cas entier

on cherche à maximiser $4x-3y$ sous les contraintes

\begin{align}
0\leq x\\
0\leq y\\
2x+y\leq2\\
x+2y\leq 2\\
\end{align}
avec $x$ et $y$ des entiers.

### Exercice 10min -> 11h30

1. Essayer d'utiliser `linprog`.
2. Dessiner le domaine de maximisation.